/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_LPUART0RXSRC_LPUART_RX 0x00u /*!<@brief LPUART0 Receive Data Source Select: LPUART_RX pin */
#define SOPT5_LPUART0TXSRC_LPUART_TX 0x00u /*!<@brief LPUART0 Transmit Data Source Select: LPUART0_TX pin */

/*! @name PORTB0 (number 16), LED_YELLOW
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_YELLOW_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LED_YELLOW_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_YELLOW_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_YELLOW_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_YELLOW_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_YELLOW_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTB1 (number 17), LED_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_RED_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LED_RED_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_RED_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_RED_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_RED_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_RED_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTB18 (number 23), REG_OUT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_REG_OUT_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_REG_OUT_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_REG_OUT_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_REG_OUT_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_REG_OUT_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_REG_OUT_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTC5 (number 41), BTN_INT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BTN_INT_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_BTN_INT_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_BTN_INT_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BTN_INT_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BTN_INT_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BTN_INT_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC16 (number 45), LED_GREEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_GREEN_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_GREEN_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_GREEN_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTC17 (number 46), BTN_OK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BTN_OK_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_BTN_OK_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_BTN_OK_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BTN_OK_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BTN_OK_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BTN_OK_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC18 (number 47), DP_RST
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DP_RST_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_DP_RST_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DP_RST_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DP_RST_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DP_RST_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DP_RST_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC19 (number 48), DP_BUSY
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DP_BUSY_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_DP_BUSY_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DP_BUSY_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DP_BUSY_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DP_BUSY_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DP_BUSY_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
