/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTA18 (number 6), BTN_INT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BTN_INT_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_BTN_INT_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_BTN_INT_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BTN_INT_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BTN_INT_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BTN_INT_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTB0 (number 16), LED_YELLOW
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_YELLOW_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LED_YELLOW_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_YELLOW_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_YELLOW_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_YELLOW_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_YELLOW_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTB18 (number 23), LED_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_RED_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LED_RED_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_RED_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_RED_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_RED_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_RED_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTC5 (number 41), CHG_PG
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CHG_PG_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_CHG_PG_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CHG_PG_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CHG_PG_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CHG_PG_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CHG_PG_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTC17 (number 46), CHG_ROG
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CHG_RUN_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_CHG_RUN_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CHG_RUN_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CHG_RUN_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CHG_RUN_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CHG_RUN_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTC18 (number 47), CHG_DONE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CHG_DONE_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_CHG_DONE_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CHG_DONE_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CHG_DONE_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CHG_DONE_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CHG_DONE_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
